
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shophaven
  labels:
    app: shophaven
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shophaven
  template:
    metadata:
      labels:
        app: shophaven
    spec:
      containers:
      - name: shophaven
        image: shophaven:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
