
apiVersion: v1
kind: Service
metadata:
  name: shophaven
  labels:
    app: shophaven
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: shophaven
  type: ClusterIP
